### ISSUE TITLE
Plop doesn't work in manually placed biomes 

### ISSUE THREAD

**Issue by PulsarGH** [replaceitem/scarpet-additions#12]
I recently created an empty void world for a map project that I am working on, and it involves setting coordinate specific borders for each biome in the world. After changing a large area (16x16 chunks from y,0 to y,319) to a deep ocean biome, I attempted to plop an ocean monument at y,62 in the center of this space. I received a false output. After testing this problem in an empty deep ocean world, I found that plop works just fine. Have I perhaps missed something? I am playing in the most current version of Minecraft. 1.20.1. Thanks!

**Comment by replaceitem** [comment]
It looks like this issue is not related to the scarpet-additions extension, but rather an issue with scarpet itself. I suggest you ask in the [carpet mod discord](https://discord.gg/gn99m4QRY4) in the #scarpet-programming-help channel, or make an issue in the [carpet mod github repo](https://github.com/gnembon/fabric-carpet).
