### ISSUE TITLE
[Suggestion] Add optional argument of column to virtual_inventory()

### ISSUE THREAD

**Issue by Ghoulboy78** [replaceitem/scarpet-additions#3]
This would allow to make variable sized inventories, and with a bit of creativity allow to make bundles which you can modify contents of from ingame.

**Comment by replaceitem** [comment]
I get what youre saying, but to me its doesn't make much sense, since the ContainerScreenHandlers always have 9 columns, and 1-6 rows. Not sure what the benefit of having a virtual inventory of e.g. 3x4 size would be. It would only be asking for trouble with syncing opened inventories if the slot count doesnt match. The only other thing that could be done to make it more flexible is to allow inventories with 1 row (and 9 columns) to be opened in a dispenser inventory layout (so 3x3) and maybe a hopper layout (5x1), and ignoring the last 4 slots of a 1row inventory.

So your idea was to create bundle like things, and change the inventory size depending on how full it is (like the vanilla thing that pops up when you hover a bundle)?

if you didnt get what i mean, take a look at net.minecraft.screen.GenericContainerScreenHandler and net.minecraft.screen.ScreenHandlerType maybe

**Comment by replaceitem** [comment]
Virtual inventories removed in favor of gnembon/fabric-carpet#888
